require 'rubygems'
require 'rake'

begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.name = "cuke4nuke"
    gem.summary = %Q{Cucumber for .NET}
    gem.description = %Q{Runs Cucumber with .NET step definitions.}
    gem.email = "richard@humanizingwork.com"
    gem.homepage = "http://github.com/richardlawrence/Cuke4Nuke"
    gem.authors = ["Richard Lawrence"]
    
    gem.add_dependency "cucumber", "0.4.4"
    gem.add_dependency "win32-process", "0.6.1"
    gem.add_dependency "systemu", "1.2.0"
  end
rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: sudo gem install jeweler"
end

